#!/bin/bash

while true
do
   clear
   echo "Battery Level Changer v1"
   echo "========================"
   echo "1-> Start script"
   echo "2-> Setup script"
   echo "3-> Exit"
   read -e -p ">>>" royna

   if [[ $royna == 1 ]]
   then

      while [[ $royna == 1 ]]
      do
         clear
         echo "Battery Level Changer v1"
         echo "========================"
         echo "Choose an option"
         echo
         echo "1-> Change battery level"
         echo "2-> Reset to default"
         echo "3-> Go back"
         read -e -p ">>>" kevios
         if [[ $kevios == 1 ]]
         then
            clear
            echo "Battery Level Changer v1"
            echo "========================"
            echo "Enter a number below"
            echo
            read -e -p ">>>" alex
            if [[ -z $alex ]]
            then
               echo "Enter some number bro..."
               sleep 2
            else
               su -c dumpsys battery set level $alex
               kevios=0
            fi
         elif [[ $kevios == 2 ]]
         then
            su -c dumpsys battery reset level
         elif [[ $kevios == 3 ]]
         then
            break
         fi
      done

   elif [[ $royna == 2 ]]
   then
      clear
      echo "Battery Level Changer v1"
      echo "========================"
      echo "Set up script (info)"
      echo
      echo "you need root access, no additional packages or stuff"
      echo "so please do grant root to Termux"
      echo "press any key to go back"
      read -e -p ">>>" FPSensor_is_gay_and_he_knows_it

   elif [[ $royna == 3 ]]
   then
      exit

   fi #roynatech if
done #while true done
