#!/bin/bash

function blud () {
if [[ $ban == $1 ]]
then
eval "$2"
fi }
while true
do
clear
echo "BombScripts v1"
echo "==============="
echo "Select a script"
echo
echo "1-> Decimal Battery"
echo "2-> Battery Level Changer"
echo "3-> IP Address Adder"
echo "X-> Exit"
echo
read -e -p ">>>" ban
blud 1 "file=DecimalBattery"
blud 2 "file=BatteryLevelChanger"
blud 3 "file=IPAdd"
blud x "exit"
blud X "exit"
chmod +x ${file} && chmod 777 ${file} && ./${file}
done
