#!/bin/bash

function blud () {
if [[ $1 == $2 ]]
then
eval "$3"
fi
}
while true
do
clear
echo "BombScripts v1"
echo "==============="
echo "Select a script"
echo
echo "1-> Decimal Battery"
echo "2-> Battery Level Changer"
echo "3-> IP Address Adder"
echo "X-> Exit"
echo
read -e -p ">>>" ban
blud $ban 1 "file='DecimalBattery'"
#if [[ $ban == "1" ]]
#then
#file="DecimalBattery"
#elif [[ $ban == "2" ]]
#then
#file="BatteryLevelChanger"
#elif [[ $ban == "3" ]]
#then
#file="IPAdd"
#elif [[ $ban == "x" ]]
#then
#exit
#elif [[ $ban == "X" ]]
#then
#clear && exit
#fi
chmod +x ${file} && chmod 777 ${file} && ./${file}
done
