#!/bin/bash
brc="/data/data/com.termux/files/usr/etc/bash.bashrc"
dir="/sys/class/power_supply/battery/charge_counter"
NUMBER='^[0-9]+$'

# BRC SAVE SAVE_NAME SAVE_VALUE
# VARIABLE=`BRC LOAD SAVE_NAME`
# BRC REMOVE SAVE_NAME
function BRC () {
 if [[ $1 == "SAVE" ]]
 then
  echo -e "#<DecimalBattery_$2>$3</DecimalBattery_$2>" >> $brc
 elif [[ $1 == "LOAD" ]]
  then
  cat $brc | grep -o -P "(?<=#<DecimalBattery_$2>).*(?=</DecimalBattery_$2>)"
 elif [[ $1 == "REMOVE" ]]
 then
  sed -i "/#<DecimalBattery_$2>/d" $brc
 fi
}

# VARIABLE=`GET`
function GET () {
 GET_1=`cat $dir`;echo -e "scale=2; $GET_1 / 30000" | bc
}

# COND VAR VALUE ON_EQUAL ON_ELSE_OPTIONAL
# COND -X VAR
function COND () {
 if [[ $1 == "-C" ]];then
 if [[ $2 == "c" ]];then clear; elif [[ $2 == "C" ]]; then clear;fi;if [[ -z $3 ]]; then :;else $3;fi;fi;if [[ $1 == "-X" ]];then if [[ $2 == "x" ]];then clear && exit; elif [[ $2 == "X" ]];then clear && exit;fi;else if [[ $1 == $2 ]];then $3;else if [[ -z $4 ]];then :;else $4;fi;fi;fi
}

function DB () {
 if [[ $1 == "NOTIFY" ]]; then
  PRINT 1
  while true;do
   LEVEL=`GET`
   su -lp 2000 -c "cmd notification post -S bigtext -t 'Battery Percentage' 'DecimalPercentage' '$LEVEL'"
   echo -e "[OK]Attempted to post notification with level '$LEVEL'"
   echo -e "[ZZ]Sleeping for '$WAIT' second(s)"
   sleep $WAIT
   echo
  done
 elif [[ $1 == "TEXT" ]]; then
  PRINT 2
  while true;do
  read TEXT_1
  if [[ $TEXT_1 == x ]];then break; elif [[ $TEXT_1 == X ]]; then break; fi
  COND -C $TEXT_1 "PRINT 2"
  if [[ -z $TEXT_1 ]]; then
   LEVEL=`GET`
   echo -e "[%]$LEVEL"
  fi
  done
 fi
}

# WAIT_CONF
function WAIT_CONF () {
 while true
 do
 PRINT 3
 read -e -p ">>>" WAIT_CONF_1
 if [[ $WAIT_CONF_1 == x ]];then break;elif [[ $WAIT_CONF_1 == X ]]; then break; fi
 if [[ $WAIT_CONF_1 =~ $NUMBER ]]; then WAIT=$WAIT_CONF_1; else echo "Numbers only" && sleep 1.5;fi
 BRC REMOVE Refresh;BRC SAVE Refresh $WAIT_CONF_1
 done
}

TESTFOR_1=`BRC LOAD IExist`
if [[ -z $TESTFOR_1 ]]
then
 clear;echo "Welcome to Decimal Battery";echo;echo "For this script to work you must:";echo "-> Grant root access to Terminal";echo "-> Install bc";echo;echo "which can be done by:";echo "-> su -c pwd && pkg install bc";echo;echo "Enter -> Don't show this again"
 echo;read -e -p ">>>" PAGE_0
 if [[ -z $PAGE_0 ]]
  then
  BRC SAVE IExist AvgA90Enjoyer
 fi
fi
TESTFOR_2=`BRC LOAD Refresh`
if [[ -z $TESTFOR_2 ]]
then
 BRC SAVE Refresh 10
 WAIT=10
else
 WAIT=$TESTFOR_2
fi

function PRINT () {
 if [[ $1 == 0 ]]
 then
  clear
  echo "Decimal Battery [Clean]"
  echo "======================="
  echo "1-> As A Notify"
  echo "2-> In Terminal"
  echo "3-> Set Refresh"
  echo "X-> Exit";echo
 elif [[ $1 == 1 ]]
 then
  clear
  echo "Decimal Battery [Notify]"
  echo "========================"
  echo "Logs";echo
 elif [[ $1 == 2 ]]
 then
  clear
  echo "Decimal Battery [Terminal]"
  echo "=========================="
  echo "Logs";echo
  echo "[!]Press enter to refresh"
  echo "[!]Press C to clear"
  echo "[!]Press X to Go back"
 elif [[ $1 == 3 ]]
 then
  clear
  echo "Decimal Battery [Config]"
  echo "========================"
  echo "Set Refresh"
  echo -e "Current Value: $WAIT"
  echo "X-> Go back";echo
 fi
}

while true;do
 PRINT 0
 read -e -p ">>>" PAGE_1
 COND -X $PAGE_1
 COND $PAGE_1 1 "DB NOTIFY"
 COND $PAGE_1 2 "DB TEXT"
 COND $PAGE_1 3 "WAIT_CONF"
done
