#!/bin/bash

function blud () {
if [[ $ban == $1 ]]
then
eval "$2"
fi }
while true
do
clear
echo "BombScripts v1"
echo "==============="
echo "Select a script"
echo
echo "1-> Decimal Battery"
echo "2-> Decimal Battery Clean"
echo "3-> Battery Level Changer"
echo "4-> IP Address Adder"
echo "5-> Display Resolution Changer"
echo "6-> BQP"
echo "X-> Exit"
echo
read -e -p ">>>" ban
blud 1 "file=DB"
blud 2 "file=DBC"
blud 3 "file=BLC"
blud 4 "file=IPA"
blud 5 "file=DRC"
blud 6 "file=BQP"
blud x "exit"
blud X "exit"
chmod +x ${file} && chmod 777 ${file} && ./${file}
done
