#!/bin/bash

blud() { [[ $ban == $1 ]] && eval "$2";}
while true; do clear
echo "BombScripts v2"
echo "==============="
echo "Select a script"
echo
echo "1-> Decimal Battery"
echo "2-> Decimal Battery Clean"
echo "3-> Battery Level Changer"
echo "4-> IP Address Adder"
echo "5-> Display Resolution Changer"
echo "6-> BQP"
echo "7-> Celler"
echo "8-> Penger"
echo "X-> Exit"
echo
read -e -p ">>>" ban
blud 1 "file=DB"
blud 2 "file=DBC"
blud 3 "file=BLC"
blud 4 "file=IPA"
blud 5 "file=DRC"
blud 6 "file=BQP"
blud 7 "file=CELL"
blud 8 "file=PENG"
blud x "exit"
blud X "exit"
chmod +x ${file} && ./${file}
done
